### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by monolidth** [OlegAlexander/lakos#1]
I have no issue, I only appreciate the work. 

Thank you :)

**Comment by monolidth** [comment]
btw. is there a reason why you use "##" in your commit messages?

**Comment by OlegAlexander** [comment]
Thank you very much, @monolidth. I really appreciate your kind words. 

To answer your question, sometimes I copy the list of changes directly from the CHANGELOG.md and make that my commit message.

**Comment by monolidth** [comment]
Is there any way to exclude the generated package. I used "-i generated" but it does not seem to work. 

![image](https://user-images.githubusercontent.com/71930307/116916358-82b08d80-ac4d-11eb-9b79-8cf64214e850.png)

**Comment by OlegAlexander** [comment]
The `--ignore` flag uses the [glob](https://pub.dev/packages/glob) package for parsing. Please try `-i generated/**`.

**Comment by monolidth** [comment]
Does not work for me :(

**Comment by OlegAlexander** [comment]
Is your project public on github? If so, I can try it on my end.

**Comment by monolidth** [comment]
Yes, you can find the repo [here](https://github.com/ReceiptManager/receipt-manager-app) :)

Thanks in advance

**Comment by OlegAlexander** [comment]
I was able to try it.

```console
cd receipt-manager-app
lakos -m -i lib/generated/** . | dot -Tpng -Gdpi=200 -o receipt-manager-app.png
```

Here's the result:

![receipt-manager-app](https://user-images.githubusercontent.com/42989765/116922633-7f47e280-ac0a-11eb-94eb-20777a06b2b0.png)

Please let me know if that works for you.

**Comment by OlegAlexander** [comment]
BTW, multiple folders can be ignored like this: `lakos -m -i {lib/generated/**,lib/device/**} . | dot -Tpng -Gdpi=200 -o receipt-manager-app.png`

**Comment by monolidth** [comment]
Thank you for your investigation and help. I really appreciate that! 

I highly suggest to write an article about this cool project. Anyway, keep it up.

Regards,
William
