### ISSUE TITLE
Bigger rectangles for most used classes

### ISSUE THREAD

**Issue by tijee** [OlegAlexander/lakos#11]
Hi, thank you for your work!

Would it be possible to create bigger rectangles for the most used classes? It would be useful to see god objects, or classes that need the most test coverage, etc.

Thanks

**Comment by OlegAlexander** [comment]
Hi @tijee. Thank you for the kind words.

`lakos` only graphs libraries (.dart files), not classes. But if you have only one class per .dart file, then they are the same thing.

In your case, I recommend turning on `--metrics --node-metrics` and then looking at the **inDegree** values. Nodes with a high inDegree are the "most used". The same goes for nodes with **instability** close to 0. 

Does this solve your issue?

**Comment by tijee** [comment]
@OlegAlexander I tried it and it gives indeed useful information. Maybe I should try to output a sorted list of these dependencies instead of a graph.
Thanks for your help 👍
