### ISSUE TITLE
Display only repositories

### ISSUE THREAD

**Issue by TitouanBourveauEXFO** [OlegAlexander/lakos#12]
I think it can be a good add to allow displaying only repositories to avoid unreadable graph for big project.

Like specify the deepness we want.

**Comment by OlegAlexander** [comment]
Sorry I missed this! 

Could you please clarify what you mean by "display only repositories"? Do you mean to display only the folders without the dart files inside?

Also, what do you mean by "specify the deepness"? Do you mean you only want to recurse into a root folder up to a certain depth?

**Comment by TitouanBourveauEXFO** [comment]
I mean "to display only the folders without the dart files inside" because in huge project display all dart files become really messy.

**Comment by OlegAlexander** [comment]
Then I'd recommend playing with the Graphviz styling. For example:

```console
lakos . | dot -Tpng -Gdpi=200 -Nshape=point -Nstyle=invis -Estyle=invis -o folders_only.png
```

which looks something like this:

![example](https://github.com/OlegAlexander/lakos/assets/42989765/040ad816-a480-433d-a954-15e0b4e25953)

Would this solution work for you?

**Comment by TitouanBourveauEXFO** [comment]
I'm don't think so because we still have the same amount of arrow. It's better tho but it's will be perfect if link can be made directly  between folder.

**Comment by OlegAlexander** [comment]
I understand what you mean now. You want an option for folders to be the nodes in the graph instead of the dart files. I'm sorry, but I will not be supporting this feature. As a workaround, you can use the `tree` command to visualize the folder structure. The `tree` command is available on both Windows and Linux. The output looks something like this:

```console
C:\Users\olega\Documents\github\lakos>tree
Folder PATH listing for volume Local Disk
Volume serial number is FFFF-EEEE
C:.
├───.dart_tool
│   ├───pub
│   │   └───incremental
│   │       └───test
│   └───test
├───bin
├───example
├───lib
│   └───src
└───test
    └───pub_cache
        └───src
```
