### ISSUE TITLE
[Question] How did you get the readme output on yEd

### ISSUE THREAD

**Issue by cedvdb** [OlegAlexander/lakos#14]
This is a question about the yEd output you have in the readme (so it's not really related to the package):

![image](https://user-images.githubusercontent.com/42989765/93006268-f3fcce00-f50e-11ea-9f96-e6ce9c8cffbb.png)

When loading the gml into yEd I just have a black blob of text which are all file names superimposed onto each other.  After playing around a bit I could press "layout" > "one click layout" to view the graph in a bit more ordered fashion, then select all nodes and apply a shape. However I could not replicate what you have done in the readme.

So my questions are:

  - How did you make the yellow boxes fit each file name ? 
  - Which layout process did you use ?

I selected all names and applied a shape to all with a given width but some names are bigger than the width, some are smaller

![image](https://github.com/OlegAlexander/lakos/assets/22280985/b8cc49d1-49e5-4d67-9a10-1f2b0549d9dd)

![image](https://github.com/OlegAlexander/lakos/assets/22280985/c4f90c76-9aa6-48dd-9736-f355aa1d9b38)

**Comment by OlegAlexander** [comment]
I'm so sorry but I don't remember exactly how I did it. I haven't used yEd in a long time. I think I just played with the layout and shape settings. Also, I may have cheated a little by moving some of the nodes manually.
