### ISSUE TITLE
Ignore multiple folders

### ISSUE THREAD

**Issue by Mighty683** [OlegAlexander/lakos#2]
Is it possible to ignore multiple folders?

For now I am able to ignore one folder:
`lakos --metrics --no-tree -i lib/extensions/** . | dot -Tpng -o graph.png`

This will ignore `lib/extensions` but beside that I want to ignore another folder eg: `tests`.

If this is not possible I believe it would be nice feature.

**Comment by OlegAlexander** [comment]
I believe you should be able to do it this way:

```console
lakos --metrics --no-tree -i {lib/extensions/**,test/**} . | dot -Tpng -o graph.png
```

I'm using the glob package, so any glob string should work, e.g. https://pub.dev/packages/glob#match-one-of-several-possibilities-

**Comment by Mighty683** [comment]
Thank you for tip 👍

**Comment by Statyk7** [comment]
I'm using the curly brackets notation to exclude multiple folders with the same name but it seems it is not recursive:
`lakos --metrics --no-tree -i {lib/extensions/**,test/**} . | dot -Tpng -o graph.png`
I tried that but no success:
`lakos --metrics --no-tree -i {lib/extensions/**,**/test/**} . | dot -Tpng -o graph.png`
Any idea?

**Comment by OlegAlexander** [comment]
Hi @Statyk7, sometimes (depending on the OS) adding quotes around the curly braces helps:

```
lakos --metrics --no-tree -i "{lib/extensions/**,test/**}" . | dot -Tpng -o graph.png 
```

**Comment by Statyk7** [comment]
Thanks Oleg, I tried that but still no difference... I'm on MacOS btw.

**Comment by OlegAlexander** [comment]
Hmm. How about:

```
lakos --metrics --no-tree -i "{lib/extensions/**.dart,test/**.dart}" . | dot -Tpng -o graph.png 
```

Also, please try it without `--no-tree`.

**Comment by Statyk7** [comment]
Same thing :( 
I don't use `--no-tree`

**Comment by OlegAlexander** [comment]
Hi @Statyk7, I'm sorry, I'm out of ideas :) Please let me know if you find a fix.

**Comment by Statyk7** [comment]
No worries, as a workaround I just enumerate all the folders I need to exclude, it's not a lot so it's ok, but thanks for your help!
