### ISSUE TITLE
Getting error in console: `RangeError (index): Invalid value: Valid value range is empty: 0`

### ISSUE THREAD

**Issue by Luckey-Elijah** [OlegAlexander/lakos#3]
When trying to execute `lakos --metrics .` I recieve the error: `RangeError (index): Invalid value: Valid value range is empty: 0` in my console. Unfortunately, there isn't anything else printed in the console.

**Comment by Luckey-Elijah** [comment]
I am unable to provide a lot detail on my [work] machine but I cloned the repo and updated the try-catches to include printing the stack.

```
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List._setIndexed (dart:core-patch/growable_array.dart:262:73)
#1      List.[]= (dart:core-patch/growable_array.dart:258:5)
#2      resolvePackageFileFromPubspecYaml (package:lakos/src/resolve_imports.dart:39:23)
#3      getEdges (package:lakos/src/build_model.dart:161:15)
#4      buildModel (package:lakos/src/build_model.dart:251:7)
#5      main (file:///Users/h009145/Development/lakos/bin/lakos.dart:104:13)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by OlegAlexander** [comment]
Thank you for reporting this. Is your project available on Github? If not, could you please attach a zip file of your project so I can try to reproduce this error?

**Comment by Luckey-Elijah** [comment]
Hi @OlegAlexander please see above. I can try my best to create a minimal, re-producable example at a later time.

**Comment by OlegAlexander** [comment]
Yes, looks like we both commented at almost the exact same time :) A minimal reproducible example would be a great starting point. Thanks.

**Comment by Luckey-Elijah** [comment]
Hi, @OlegAlexander. I have successfully created a minimal reproducible example at [Luckey-Elijah/lakos/tree/fail-example](https://github.com/Luckey-Elijah/lakos/tree/fail-example) in directory `fail_example/`.

They culprit is how a dart allows an import with a line break like this:
```dart
import 'package:'
    'fail_example/helper.dart';

void main(List<String> arguments) {
  print('Hello, $myString!');
}
```

**Comment by OlegAlexander** [comment]
Whoa, I had no idea Dart allows this syntax! Given how infrequently this syntax would come up, I'm inclined not to support it. However, I will add this syntax as a test case and maybe print a more descriptive error message.

Let's keep this issue open for now. Meanwhile, please try the normal single-line import syntax. Thanks for putting the failure case together and for identifying the problem!

**Comment by Luckey-Elijah** [comment]
Yes. It works now that I've correct the import line. After inspecting your implementation for parsing the import lines, I can imagine it would be a relatively large effort to accommodate this edge case.

**Comment by OlegAlexander** [comment]
Maybe I can parse it if I use the semicolon as a terminator...

**Comment by OlegAlexander** [comment]
I've added a check to ignore import lines that don't end with a semicolon in lakos 2.0.2.
