### ISSUE TITLE
"no root directory found" error with options

### ISSUE THREAD

**Issue by lukepighetti** [OlegAlexander/lakos#6]
`lakos .` works as expected

`lakos -i **/*.g.dart .` gives the error "no root directory found"

could this have to do with glob expansion in `zsh` on macOS?

Edit: it looks like this works on zsh / macOS

`lakos -i \*\*/\*.g.dart .`

**Comment by OlegAlexander** [comment]
Does it work in quotes?

**Comment by lukepighetti** [comment]
Yes

**Comment by Adrian-Samoticha** [comment]
I've had the same issue on zsh/macOS. The readme suggests that should work without quotes, but it only works in quotes.
