### ISSUE TITLE
-m option doesn't complete

### ISSUE THREAD

**Issue by lukepighetti** [OlegAlexander/lakos#7]
Running this on a fairly large codebase, the `-m` option hangs for more than 15 minutes. As a comparison, a straightforward run of Lakos takes 0.75s

**Comment by OlegAlexander** [comment]
The biggest package I've ever tried Lakos on is [Dart Analyzer](https://pub.dev/packages/analyzer). It has 1288 files, 391310 LOC, and many cycles. Lakos takes  20 seconds to run on this package with the -m option. Is your package bigger than Analyzer?

If you're piping the output of lakos directly into graphviz dot, could you please try running lakos by itself and timing it? I want to make sure that it's lakos that's taking 15 minutes and not graphviz dot.

**Comment by OlegAlexander** [comment]
Hi @lukepighetti, if this is still an issue for you, then I obviously need to do some profiling. Maybe there's something unique about your project that I haven't encountered before in my tests. If your project is public, please send me a link so I can try to recreate the issue.

**Comment by OlegAlexander** [comment]
Cannot reproduce.
