### ISSUE TITLE
Show external packages

### ISSUE THREAD

**Issue by lukepighetti** [OlegAlexander/lakos#8]
Would be nice if lakos had an option to also quantify which files/projects are importing external dependencies

**Comment by OlegAlexander** [comment]
That feature is out of scope for lakos. For external dependencies, please try `dart pub deps` or the [pubviz package](https://pub.dev/packages/pubviz).

**Comment by lukepighetti** [comment]
Do you happen to know of any tools that allow us to see which files are importing which external packages?

**Comment by OlegAlexander** [comment]
Hi @lukepighetti, lakos parses all imports in the [getEgdes function](https://github.com/OlegAlexander/lakos/blob/master/lib/src/build_model.dart#L139), but then I filter out the external imports on [this line](https://github.com/OlegAlexander/lakos/blob/master/lib/src/build_model.dart#L177). You can try commenting out that line and see if that does what you want. 

The reason I keep only the internal imports is that external imports make the graph ugly and also should not be counted in the metrics. Maybe in the future, I'll consider keeping external imports but marking them in a different color and not counting them in the metrics.

**Comment by lukepighetti** [comment]
Seems like a feature that would be easy to add with a CLI flag. I'm pulling the data into a pandas dataframe anyway, and building my own graphs.

**Comment by OlegAlexander** [comment]
Hi @lukepighetti, to clarify, you want to show just top-level external imports, without recursively following all external imports, and without counting external files in the metrics. Is this correct?

**Comment by lukepighetti** [comment]
If a file is a node, some metadata on the node that states which external packages it imported would be fine. Or it could be blended into the graph somehow, but I'm not sure what that would look like.

**Comment by OlegAlexander** [comment]
That sounds doable 😊 I'll consider adding that to the json output in the next release. If I were to graph it, the external files would be floating outside the project directory structure--I can try it and see if I can make it work visually.

**Comment by OlegAlexander** [comment]
After 2+ years, I think it's fair to say this will not get done.
