### ISSUE TITLE
part files are set as orphin nodes.

### ISSUE THREAD

**Issue by cedvdb** [OlegAlexander/lakos#9]
`_x` included as `part`  should either be ignored or have the correct parent wouldn't it ?

**Comment by OlegAlexander** [comment]
Sorry, could you please give a longer example and include a screenshot of the diagram? Lakos doesn't support the `part` directive at all.

**Comment by cedvdb** [comment]
Here is what it looks like:

![image](https://user-images.githubusercontent.com/22280985/196157163-27c27d93-ef73-4c87-9bb2-15619d292cba.png)


The arrows are lost as the private classes are set as orphans. Is there a technical issue related to dart in following the dependency here ?

I would say there would need to be an option to hide those dependencies too.  

Note: I'm not asking for you to do it, I'm just setting an issue to start of the discussion so this can be fixed by *someone*.

**Comment by OlegAlexander** [comment]
Thanks @cedvdb. My understanding is that `part` is used rarely in Dart, but I could be wrong. If I were to support `part` it would probably look like another arrow type, like a dotted arrow line or something. What do you think? Let's keep this issue open for now...

**Comment by cedvdb** [comment]
@OlegAlexander I personally use it extensively, as I want my libraries to be properly encapsulated. I've seen it used in bigger google projects too, (maybe the dart sdk, I don't remember which project).

As for arrows, there is two scenario: A class can be included in another file with `part` : 

 - If the class included is public (not starting with `_`), there should be an arrow for anyone using it
 - It the class included is private, the intent of the developer is to encapsulate this part of the library, so by definition I think the better way would be to not have it at all part of the graph. This is usually the most common scenario.

**Comment by OlegAlexander** [comment]
That makes sense. But just to be clear, are you talking about class names or file names that start with `_`? Because Lakos only looks at file names.

**Comment by cedvdb** [comment]
>  Because Lakos only looks at file names.

Personally by convention I use `_` when the internal class of the file also starts with `_`. I'd suspect others to do the same but I cannot be certain.


A setup a flag to be able to switch between an encapsulated view  and one where the part files are also part of the graph would be the best option in my opinion. However after checking the source, just omitting seems like it would be an okay first step.

To have the part files part of the graph it seems like the function `getEdges` would need to include those part refs:

https://github.com/OlegAlexander/lakos/blob/master/lib/src/build_model.dart#L12

To have the part files not part of the graph it seems the function `getDartFiles` would need to omit `_` , the Glob class does not support omitting matches, so I guess a `.whereNot((file) => file.path.startWith('_')`  would do:

https://github.com/OlegAlexander/lakos/blob/master/lib/src/build_model.dart#L109


It seems that the second scenario would be easy to implement, not sure about the first one. Since nobody complained beside myself just having the second method would fit the library philosophy ?

**Comment by OlegAlexander** [comment]
Thank you for identifying where in my code the changes could be made. I agree that the second scenario would be easier, but I'm not convinced that many people use the `_` convention. For example, none of the libs in my test suite use it. 

Having said that, you can ignore a list of specific files like this:

```console
lakos -i "{**_suggestions_list_view.dart,**_suggestions_data_source.dart,**_search_suggestion_input.dart}" .
```

Would that work for you as a workaround?

**Comment by cedvdb** [comment]
Yup that can work as a workaround, this is sufficient for me personally so feel free to close it or let it open in case of someone wanting to implement the edges in part.

`lakos.bat -o metrics/metrics.dot -m ./lib/src -i "_**.dart"  && dot -Tsvg metrics/metrics.dot -o metrics/metrics.svg && gv2gml metrics/metrics.dot  -o metrics/metrics.gml`


Here are some usages of part by the dart sdk https://github.com/dart-lang/sdk/search?q=part

**Comment by ookami-kb** [comment]
> My understanding is that `part` is used rarely in Dart, but I could be wrong. If I were to support `part` it would probably look like another arrow type, like a dotted arrow line or something. What do you think? Let's keep this issue open for now...

Hi, my 2 cents about this.

Part files are used pretty extensively by code generation tools, also, they may come in handy for other use cases. My main use case is e.g. for bloc files where you have `bloc` + `state` + `event` files tightly coupled, so I often make `state` and `event` parts of `bloc` file.

For me, it makes sense to just ignore these files, since neither can there be imports inside them nor can they be imported by other files. So, if the file contains `part of "...";` line it can be safely ignored.

**Comment by OlegAlexander** [comment]
Thanks for the explanation, @ookami-kb! 

@cedvdb, do you agree that files containing `part of` should be ignored?

**Comment by tripplilley** [comment]
> do you agree that files containing `part of` should be ignored?

I'm not OP, but +1 on ignoring `part of` (or at least as an option).

In my ideal world, I'd have something that would visually group the containing file (the one with the `part` directive) and its constituent parts (those with the `part of` directives), so I could "see" the multi-file nature of the effective import. Alternatively, having a modified appearance for the containing file, combined with ignoring the constituent files, would at least prompt my awareness that "there's more there, there."

Having "partness" be a part of the metrics would also be helpful, I think. Perhaps in the containing file, putting the transitive count of contained files (e.g., `numParts: 2` if a container had either two `part` directives, or one `part` directive which itself also had a `part` directive).

**Comment by OlegAlexander** [comment]
Hi @tripplilley, thank you for your thoughtful reply. I like the idea of adding an option to ignore `part of` directives. Would you like to take a stab at it and submit a PR?

I like the idea of having "partness" in the metrics, too. But I'm not sure this feature will be worth the effort because I'm still not sure how prevalent the usage of `part` is. 

Do you know of a package that uses 'part' a lot that I can use for testing? I tried a Github search [here](https://github.com/search?q=%22part+of%22+.dart&type=Code) but found very little.
